library(shiny)
shinyUI(pageWithSidebar(
  headerPanel("the prediction of the Miles/gallon of cars"),
  sidebarPanel(
    selectInput("cyl","Number of cylinders",
                       c("4"=4,
                         "6"=6,
                         "8"=8)),
    sliderInput("disp","Displacement (cu.in.)",value=230,min=70,max=500,step=0.1,),
    sliderInput("hp","Gross horsepower",value=150,min=50,max=350,step=0.1,),
    sliderInput("drat","Rear axle ratio",value=3.5,min=2.5,max=5,step=0.01,),
    sliderInput("wt","Weight (lb/1000)",value=3.2,min=1.5,max=5.5,step=0.01,),
    sliderInput("qsec","1/4 mile time",value=18,min=10,max=25,step=0.1,),
    radioButtons("vs","V/S",
                c("V"=0,
                  "S"=1)),
    radioButtons("am","Transmission",
                c("automatic"=0,
                  "manual"=1)),
    numericInput("gear","Number of forward gears", 3 ,min = 3,max = 5,step = 1),
    numericInput("carb","Number of carburetors", 1 ,min = 1,max = 8,step = 1)
),
  mainPanel(h3('Results of the prediction'),
            h4('Which resulted in a prediction of the Miles/gallon of cars'),
            verbatimTextOutput("prediction"),
            plotOutput('newplot'),
            h3('You entered'),
            h5("Number of cylinders"),
            verbatimTextOutput("cyl"),
            h5("Displacement (cu.in.)"),
            verbatimTextOutput("disp"),
            h5("Gross horsepower"),
            verbatimTextOutput('hp'),
            h5("Rear axle ratio"),
            verbatimTextOutput('drat'),
            h5("Weight (lb/1000)"),
            verbatimTextOutput('wt'),
            h5("1/4 mile time"),
            verbatimTextOutput('qsec'),
            h5("V/S"),
            verbatimTextOutput('vs'),
            h5("Transmission"),
            verbatimTextOutput('am'),
            h5("Number of forward gears"),
            verbatimTextOutput("gear"),
            h5("Number of carburetors"),
            verbatimTextOutput("carb")
            )
)
)